spring:
  application:
    name: spring6-web-security
  datasource:
    url: jdbc:mariadb://localhost:3306/dev_empdb
    username: root
    password: root
  
logging:
 level:
    root: info
    org:
      springframework:
        security: DEBUG