spring:
  application:
    name: emp-data-jpa
  datasource:
    password: root
    url: jdbc:mariadb://localhost:3306/dev_empdb
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          'batch_size: 50'
