spring:
  application:
    name: emp-data-service
  datasource:
    url: jdbc:mariadb://localhost:3306/dev_empdb
    username: root
    password: root
  jpa:
    show-sql: true
logging:
 level:
    root: warn
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
   sampling:
    probability: 1.0