spring:
  application:
    name: emp-data-service
  datasource:
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/dev_empdb}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
logging:
 level:
    root: warn
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${UREKA_SERVER_URL:http://localhost:8761/eureka}
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
   sampling:
    probability: 1.0