spring:
  application:
    name: emp-data-service
  datasource:
    url: jdbc:mariadb://localhost:3306/dev_empdb
    username: root
    password: root
  jpa:
    show-sql: true
logging:
 level:
    root: warn