server:
  port: 8180
  
spring:
  application:
    name: hr-service
logging:
  level:
    root: debug
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
       
  endpoint:
    health:
      show-details: always
      
  health:
    circuitbreakers:
      enabled: true
      
resilience4j:
  circuitbreaker:
    instances:
      hr-service-config:
       register-health-indicator: true
       sliding-window-size: 10
       sliding-window-type: COUNT_BASED
       minimum-number-of-calls: 5
       failure-rate-threshold: 50
       permitted-number-of-calls-in-half-open-state: 3
       wait-duration-in-open-state: 5s
       automatic-transition-from-open-to-half-open-enabled: true
       event-consumer-buffer-size: 15
       
      
      
      
      